### PR TITLE
Ambahm: Wk 2 Warm up tasks.

### PR DESCRIPTION
**Pull request by Ambahm**
Wk 2: Warm task Assignment

### CODE REVIEW

**Comment by cheuschober** [comment]
ok to test

**Comment by cheuschober** [comment]
@Ambahm, Please check your email for an invitation from GitHub to join our class team on GitHub. Tests will not run automatically without first joining the team and this could negatively affect your grades!

**Comment by Ambahm** [comment]
What exactly do I need to do?

**Comment by cheuschober** [comment]
@Ambahm, please see my last comment for joining the team.

Re: failed tests, you can click the test link then take a look at the violations tab and see if you can figure out what might be going wrong. Hover over any icons in the left or run the pylint tests locally (watch the video about running tests if you want help with that)

**Pull request merged**
