### PR TITLE
Week 02 warmup pull request

### PR DESCRIPTION
**Pull request by adrianjengel**
Pull request.

### CODE REVIEW

**Comment by cheuschober** [comment]
ok to test

**Comment by cheuschober** [comment]
@adrianjengel. Looks great! You should have received an email from GitHub inviting you to join our team!

**Comment by cheuschober** [comment]
@adrianjengel, FYI, we usually put the docstring directly below the coding statement, eg:

    # -*- coding: utf-8 -*-
    """My docstring"""

    proper_coding

Otherwise perfect.

**Comment by adrianjengel** [comment]
Thank you, I'll keep that in mind going forward.

**Pull request closed without merging**
