### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by eliz79**
Trying once again.

### CODE REVIEW

**Comment by cheuschober** [comment]
Hi @eliz79!

This is a good pull request, you did it right! Woot! But I don't seen any of your work for week #02 warmup. Did you remember to `git push origin master` your changes?

**Comment by eliz79** [comment]
Prof, 
I did forget to do command "git push origin master". I made the changes just now. Please review again. 

Thanks,
ELiz

**Comment by cheuschober** [comment]
retest this please

@eliz79 Let's give our butler friend a moment to get himself straightened out

**Comment by cheuschober** [comment]
retest this please

**Comment by cheuschober** [comment]
Ok! @eliz79; not sure what was up with Jenkins on that last build but this one is performing as expected. The complaint about task 3 is because you likely used an older (mistaken) direction to create it as a .py instead of a .txt and lint checks that every .py file is perfect. That-said, I can definitely say you've gotten 100% on this one and so will close it. :)

**Comment by cheuschober** [comment]
Just paste a link from this page into blackboard to get credit!

**Comment by eliz79** [comment]
Ok, Ill use (https://github.com/is210-2015-spring-01/is210-week-02-warmup/pull/2#issuecomment-73162759) for the credit of the warm-up. 
Wheww one done and unto the next one. LOL

**Pull request merged**
